Default: &defaults
  host: "localhost"
  port: 3000
  copyright: Insert copyright statement here
  analytics: UA-21596514-1
Development:
  <<: *defaults

Test:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  host: "www.casualaddict.com"
  approot: "http://www.casualaddict.com"
  port: 3000
  <<: *defaults
